<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PublicCloudDownloader.Core\PublicCloudDownloader.Core.csproj" />
    <PackageReference Include="AngleSharp" Version="1.7.1" />
  </ItemGroup>
</Project>
