<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>PublicCloudDownloader</AssemblyName>
    <RootNamespace>PublicCloudDownloader.App</RootNamespace>
    <Product>Public Cloud Downloader</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PublicCloudDownloader.Core\PublicCloudDownloader.Core.csproj" />
    <ProjectReference Include="..\PublicCloudDownloader.Infrastructure\PublicCloudDownloader.Infrastructure.csproj" />
  </ItemGroup>
</Project>
